# RUN CONSTANTS

import os

# file paths
INPUT_FILE_PATH = '../data' 

# output file
OUTPUT_FILE_PATH = '../../../project/seattle_streets/data'

# analysis file path
ANALYSIS_OUTPUT_FILE_PATH = os.path.join(OUTPUT_FILE_PATH, 'analysis')

# STEP 1 INPUT FILE NAME
S01_SND_IN_FILE_NAME = 'Street_Network_Database_SND_5117857036965774451.gpkg'

# STEP 1: OUTPUT STREET NETWORK
S01_SND_OUT_FILE_NAME = 'Street_Network_Database_Complete.gpkg'

# STEP 1: OUTPUT EXCEL FILE
S01_BST_OUT_FILE_NAME = 'blank_street_type.xlsx'

# STEP 2: INPUT FILE NAME - STREET NETWORK
S02_SND_IN_FILE_NAME = S01_SND_OUT_FILE_NAME

# STEP 2: OUTPUT FILE NAME - NODES
S02_NODE_OUT_FILE_NAME = 'Street_Network_Nodes.gpkg'

# STEP 2: INPUT EXCEL FILE WITH THE MANUALLY UPDATED STREET CLASSIFICATIONS
S02_BST_IN_FILE_NAME = 'blank_street_type_modified.xlsx'

# STEP 2: ALL STREETS IN SEATTLE
S02_SND_FULL_OUT_FILE_NAME = 'Street_Network_Database_Seattle_Full.gpkg'

# STEP 2: STREETS IN THE CITY CENTRAL PART OF THE CITY
S02_CENTRAL_STREETS_IN_FILE_NAME = 'Street_Network_Database_Seattle_Central_Streets.csv'

# STEP 2: CITY SECTIONS
S02_CITY_SECTIONS_OUT_FILE_NAME = 'city_sections.gpkg'

# STEP 2: THE WORKING STREETS IN THE CITY OF SEATTLE
S02_SND_WORKING_OUT_FILE_NAME = 'Street_Network_Database_Seattle_working.gpkg'

# STEP 3: INPUT STREETS - THE WORKING STREETS FROM STEP 2
S03_SND_WORKING_IN_FILE_NAME = S02_SND_WORKING_OUT_FILE_NAME

# STEP 3: INPUT NODES - THE NODES AS CREATED IN STEP 2
S03_NODE_IN_FILE_NAME = S02_NODE_OUT_FILE_NAME

# STEP 3: SHORTEST SEGMENT ANALYSIS
S03_SS_COUNT_OUT_FILE_NAME = 'shortest_segment_count.xlsx'

# STEP 3: MISSING SEGMENTS
S03_MISSING_OUT_FILE_NAME = 'missing_segments.gpkg'